spring:
  #profiles:
  #active: localHeroku
  application:
    name: kirschbaum
  datasource:
    url: jdbc:${profile.datasource.postgresurl}
    username: ${profile.datasource.username}
    password: ${profile.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: "/api/${spring.application.name}"

security:
  jwt:
    secret: "awijdkleilrodsjsnneidjnrukshndASSDFEA"
    expiresAfterHours: 24

