name: Deploy Kirschbaum to heroku

on:
  push:
    branches:
      - currywurst

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: lowani.jar
          path: backend/target/lowani.jar

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment: #optional, zeigt 'nur' den Link im Repo an
      name: production-heroku
      url: https://lowani-app.herokuapp.com/
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: lowani.jar
          path: backend/target
      - name: Login to heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a lowani-app
      - name: Deploy docker container
        run: heroku container:release web -a lowani-app